Db solution
7finney/lomads-interface pull request #6
Opened 2022-08-10 15:25 UTC by codecookerpro

Moralis integration to the project

2022-08-11 16:09 UTC, 0mkara requested changes

2022-08-11 16:09 UTC, 0mkara commented on src/components/AccountDetails/index.tsx
> +const AddressLink = styled(ExternalLink) <{ hasENS: boolean; isENS: boolean }>`
`(ExternalLink) <{ hasENS:`
Type definityions should not have space between.

2022-08-11 16:09 UTC, 0mkara commented on src/components/WalletModal/index.tsx
> +  const loginMoralis = async () => {
Why do we need to login to moralis? I think this is the reason for the metamask moralis popup issue.

2022-08-11 16:10 UTC, 0mkara requested changes

2022-08-11 16:10 UTC, 0mkara commented on src/pages/GoLivePage.tsx
> +    const creatingToken = await factory.createToken(tokenTitle, tokenSymbol, supply, holder, explain);
When we create a transaction we should add the transaction to the account system.

2022-08-16 16:10 UTC, 0mkara commented on .env
> +REACT_APP_IPFS_KEY=01493be23ac5ddd53beba8db5294d588
@codecookerpro pls do not commit variables. I will have to delete the app and recreate keys now. Our repo is public and we should not commit key variables to repositories.

2022-08-16 18:58 UTC, 0mkara requested changes

2022-08-16 18:58 UTC, 0mkara commented on src/utils/ipfs.ts
> +export const fetchFile = async (cid: string) => {
cid is not `string`. Please use proper types. I would prefer
```
import { CID } from "ipfs-http-client";
cid: string | CID;
```

2022-08-16 18:58 UTC, 0mkara commented on src/utils/ipfs.ts
> +    const result = await (ipfs as IPFSHTTPClient).add(coverImg);
Why should we typecast `ipfs as IPFSHTTPClient`? Instead check if `ipfs` is defined.

2022-08-21 14:23 UTC, codecookerpro commented on .env
> +REACT_APP_IPFS_KEY=01493be23ac5ddd53beba8db5294d588
i see.
i willnot commit those values in .env again.

2022-08-23 06:11 UTC, 0mkara requested changes

2022-08-23 13:13 UTC, codecookerpro commented on src/pages/GoLivePage.tsx
> +    addTransaction(creatingGovernor, transactionInfo)
const addTransaction = useTransactionAdder();
addTransaction(creatingGovernor, transactionInfo);
so it is the same as dispatch(addTransaction(creatingGovernor, transactionInfo) if you consider the useTransactionAdder() hook.

2022-08-23 13:14 UTC, codecookerpro commented on src/pages/GoLivePage.tsx
> +    addTransaction(creatingGovernor, transactionInfo)
const addTransaction = useTransactionAdder();
addTransaction(creatingGovernor, transactionInfo);
so it is the same as dispatch(addTransaction(creatingGovernor, transactionInfo) if you consider the useTransactionAdder() hook.

I am not clear what does it mean by "transaction needs to be added before transaction.wait".
Could you tell me about that?

2022-08-28 08:02 UTC, closed without merging